version: 2.1
jobs:
  build:
    docker:
      - image: cypress/browsers:node12.16.2-chrome81-ff75
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'npm install -g npm@latest'
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: MOCHA_FILE=~/junit/mocha/results.xml npm run ci-test
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          name: cypress-test
          command: npm run testcypress
      - store_test_results:
          path: ~/junit
