version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.3.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: mocha test --reporter mocha-junit-reporter --exit
          environment:
            MOCHA_FILE: ~/junit/test-results.xml
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
